Support loading hf model directly
InternLM/lmdeploy pull request #685
Opened 2023-11-14 02:21 UTC by irexyc

## Motivation

```
# original 
model = TurboMind.from_pretrained('/nvme/chenxin/download/ws-vicuna-tp1/')

# new case1, local path
model = TurboMind.from_pretrained('/nvme/shared/Qwen-7B-Chat/', model_name = 'qwen-7b')

# new case2, hf repo_id
model = TurboMind.from_pretrained('Qwen/Qwen-7B-Chat, model_name = 'qwen-7b', tp=2)

# new case3 hf repo_id managed by lmdeploy
model = TurboMind.from_pretrained('irexyc/internlm-chat-20b-4bit, tp=2, quant_policy=4)

# AutoModel
from transformers import AutoModelForCausalLM

repo_id = "irexyc/internlm-chat-20b-4bit"

model = AutoModelForCausalLM.from_pretrained(
    repo_id, proxies=proxies, trust_remote_code=True, quant_policy=4, use_context_fmha=1)

query = "How are you today?"

for res, session in model.chat(query, stream_output=True):
    print(history.message[-1][-1])
```
## Modification

Please briefly describe what modification is made in this PR.

2023-11-14 12:56 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +                local_path = download_hf_repo(pretrained_model_name_or_path,
感觉没有必要封装download_hf_repo，是不是直接 huggingface_hub.snapshot_download()就好了

2023-11-14 13:09 UTC, lvhan028 commented on lmdeploy/turbomind/hf_repo/config.json
> +        "LmdeployForCausalLM"
Can we use `LMDeployForCausalLM` and `LMDeployConfig`?

2023-11-14 13:20 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +            self.create_common_from_workspace(model_path)
`self.model_comm = self.from_workspace(model_path)`

2023-11-14 13:27 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +                Can be either:
`either` 通常表示 2个选择。"It could be one of the following options:"

2023-11-14 13:28 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +                    - 1) A path to a *directory* containing model which is
A local directory path of a turbomind model

2023-11-14 13:39 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +                    - 2) A repo_id or path which is managed by lmdeploy,
- 2) The *model_id* of a quantized model hosted inside a model repo on huggingface.co/lmdeploy
- 3) The *model_id* of a model hosted inside a model repo on huggingface.co, such as "InternLM/internlm-chat-7b", "Qwen/Qwen-7B-Chat ", "baichuan-inc/Baichuan2-7B-Chat" and so on.

2023-11-14 13:48 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +            if not is_lmdeploy_managed:
```
model_source = ModelSource.HF_LMDEPLOY if 'turbomind' in config else ModelSource.HF_MODEL

```

2023-11-14 13:50 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +            model_name (str): needed when pretrained_model_name_or_path is 3)
model_name, model_format 是在3)的时候填？

2023-11-14 14:00 UTC, lvhan028 commented
readme可以更新下，不用下载模型了

2023-11-14 14:23 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +            def _get_key(key, value):
这个函数应该是要 _get_value

2023-11-14 14:26 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +        if model_source in [ModelSource.HF_LMDEPLOY, ModelSource.HF_MODEL]:
这个convert的工作，可以在 from_hf() 中完成吗

2023-11-15 05:56 UTC, lvhan028 commented on lmdeploy/turbomind/deploy/target_model/base.py
> +            assert th_tensor.dtype in [
`th_tensor.dtype`和注释不一致

2023-11-15 06:01 UTC, lvhan028 commented on lmdeploy/turbomind/deploy/target_model/base.py
> +        elif len(self.tm_params) > 0:
没有理解这段 elif 的含义。什么时候 `self.tm_params`不为空呢？

2023-11-15 06:07 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +                self.model_comm.create_shared_weights(device_id, rank)
self.model_comm统一命名为self.tm_model吧

2023-11-15 06:18 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +            '',
这里写上 model_dir='' 吧

2023-11-15 07:01 UTC, lvhan028 commented on lmdeploy/turbomind/turbomind.py
> +            config_file = osp.join(local_path, 'config.json')
使用 config.json 中是否含有 turbomind 来判断模型的source，会不兼容用户已经量化好的模型。
是否可以通过判断 local_path 中是否含有 w4a16, kv-int8 等特殊文件呢？
@pppppM @lzhangzz 你们觉得呢？

2023-11-15 11:25 UTC, irexyc commented on lmdeploy/turbomind/turbomind.py
> +            config_file = osp.join(local_path, 'config.json')
兼容了一下之前的模型。不过之前量化好的模型要更新么，不然好像没办法做到AutoModel.from_pretrained

2023-11-15 11:26 UTC, irexyc commented on lmdeploy/turbomind/turbomind.py
> +            model_name (str): needed when pretrained_model_name_or_path is 3)
没必要，去掉了。

2023-11-16 06:26 UTC, lvhan028 requested changes

2023-11-16 06:26 UTC, lvhan028 commented on docs/zh_cn/load_hf.md
> +### 使用方式
二级目录吧

2023-11-16 06:26 UTC, lvhan028 commented on lmdeploy/lite/apis/auto_awq.py
> +    export_turbomind_hf_model(model_name,
建议在函数 auto_awq 增加参数 `to_turbomind: bool = 'False'`。
当这个变量为True时，再调用 export 函数。
这个函数名建议修改为：export_turbomind_model

2023-11-16 06:30 UTC, pppppM commented on lmdeploy/turbomind/turbomind.py
> +            config_file = osp.join(local_path, 'config.json')
config.json 这些东西更新应该问题不大，现在上传的量化模型里这些东西应该都没有被用到

2023-11-16 06:34 UTC, lvhan028 commented on docs/en/load_hf.md
> +### Usage
H2

2023-11-16 06:34 UTC, lvhan028 commented on docs/en/load_hf.md
> +#### 1) A model converted by `lmdeploy convert`
H3

2023-11-16 06:38 UTC, lvhan028 commented on docs/en/load_hf.md
> +2. A quantized model managed by [lmdeploy](https://huggingface.co/lmdeploy) or [internlm](https://huggingface.co/lmdeploy) on huggingface.co
A lmdeploy-quantized model hosted on huggingface.co, such as [llama2-70b-4bit](), [internlm-chat-20b-4bit](), etc.

2023-11-16 06:39 UTC, lvhan028 commented on docs/zh_cn/load_hf.md
> +2. huggingface.co 上面 [lmdeploy](https://huggingface.co/lmdeploy) / [internlm](https://huggingface.co/lmdeploy) 所管理的模型
参考英文文档中的comments

2023-11-17 05:45 UTC, lvhan028 commented
@AllentDan 请测试 llama2-7b-chat, internlm-chat-20b, qwen-chat-14b 的 convert -> chat  -> profile_throughput, convert->restful_api -> profile_restful_api 是否正确无误

2023-11-17 07:30 UTC, AllentDan commented
> @AllentDan 请测试 llama2-7b-chat, internlm-chat-20b, qwen-chat-14b 的 convert -> chat -> profile_throughput, convert->restful_api -> profile_restful_api 是否正确无误

Tested OK.

2023-11-17 07:34 UTC, AllentDan reviewed
I thought the PR brought huggingface configuration files like `modeling_lmdeploy.py` to *workspace* and users can use it through codes like:
```python
# AutoModel
from transformers import AutoModelForCausalLM

repo_id = "lmdeploy/turbomind-internlm-chat-7b-w4"

model = AutoModelForCausalLM.from_pretrained(
    repo_id, proxies=proxies, trust_remote_code=True)

query = "How are you today?"

for res, session in model.chat(query, stream_output=True):
    print(session.message[-1][-1])
```
Why not modeling_lmdeploy in converted *workspace*? And `AutoModelForCausalLM` can run lmdeploy backend.

2023-11-19 10:05 UTC, lvhan028 commented
> I thought the PR brought huggingface configuration files like `modeling_lmdeploy.py` to _workspace_ and users can use it through codes like:
> 
> ```python
> # AutoModel
> from transformers import AutoModelForCausalLM
> 
> repo_id = "lmdeploy/turbomind-internlm-chat-7b-w4"
> 
> model = AutoModelForCausalLM.from_pretrained(
>     repo_id, proxies=proxies, trust_remote_code=True)
> 
> query = "How are you today?"
> 
> for res, session in model.chat(query, stream_output=True):
>     print(session.message[-1][-1])
> ```
> 
> Why not modeling_lmdeploy in converted _workspace_? And `AutoModelForCausalLM` can run lmdeploy backend.

The converted model is in turbomind's model format. We are not going to upload turbomind-format model to huggingface hub.

This PR aims at deploying models from huggingface hub directly without downloading and converting them manually

2023-11-21 07:48 UTC, lvhan028 approved these changes

2023-11-22 06:26 UTC, lzhangzz commented on src/turbomind/triton_backend/llama/LlamaTritonModel.cc
>      }
```suggestion
  ft::FT_CHECK_WITH_INFO((config.empty() ^ model_dir.empty()), "...");
```

2023-11-22 09:31 UTC, AllentDan commented on lmdeploy/turbomind/chat.py
> +from .utils import get_gen_param
can we use absolute import instead of relative import? IDEs now like vscode can modify corresponding codes if the file is moved to other places.

2023-11-22 10:54 UTC, lzhangzz approved these changes

2023-11-22 11:05 UTC, merged